### PR TITLE
Update GuidesCollection.md

### PR DESCRIPTION
**Pull request by n00b69**
added guides

### CODE REVIEW

**Comment by hiprivsid** [comment]
@n00b69 what the fuck

**Comment by halal-beef** [comment]
@n00b69 Nice sneaky change on vayu

**Review by NetuserPRO — CHANGES_REQUESTED** [review]
Guide for Poco X3 Pro you linked is not official, woa-msmnile doesn't support sdm845.

**Review by sunflower2333 — APPROVED** [review]

**Review by qaz6750 — COMMENTED** [review]
It seems that there is still controversy at present. Please note that woa msmnile currently does not support SDM845. Linking the Guide for SDM845 devices here and using EDK2UEFI may mislead some people, so these need to be discussed.

**Comment by sunflower2333** [comment]
> It seems that there is still controversy at present. Please note that woa msmnile currently does not support SDM845. Linking the Guide for SDM845 devices here and using EDK2UEFI may mislead some people, so these need to be discussed.

Sounds reasonable.

**Review by halal-beef — CHANGES_REQUESTED** [review]
There was a lack of consent given to change vayus link, basis of the guide being "broken" was disproved, also only issues with the guide was a -epsilon in the drivers filename and MAYBE index used though that is extremely volatile depending on the version, target edition and iso used

**Comment by n00b69** [comment]
> There was a lack of consent given to change vayus link, basis of the guide being "broken" was disproved, also only issues with the guide was a -epsilon in the drivers filename and MAYBE index used though that is extremely volatile depending on the version, target edition and iso used

The current guide is not functional due to incorrect diskpart instructions, furthermore the lack of zip drivers can also cause issues (7z has caused many, many issues in the past). The same thing applies to the Cepheus guide, which I did not change as I did not make a version of this guide.

The guide overall is also a sloppy port from the Sduo guide, because many strings were not changed accordingly, though that does not hinder the installation of Windows.

**Comment by halal-beef** [comment]
> The current guide is not functional due to incorrect diskpart instructions

The disk part instructions are not incorrect, it works, it also instructs u what to do in diskpart in great detail as well.

The concern about it being a sloppy copy. I disagree, the only other thing beyond already mentioned was copyrights which are correct, we indeed use stuff from QC, Duo and others

**Comment by degdag** [comment]
WOA-Msmnile doesn't support SDM845 officially so I guess no need to put related guide to it on this repo

**Review by n00b69 — COMMENTED** [review]
Removed SDM845 as per several requests

**Comment by sunflower2333** [comment]
looks fine at now.

**Pull request merged**
