### PR TITLE
Fix links for some of the guides

### PR DESCRIPTION
**Pull request by remtrik**

### CODE REVIEW

**Comment by n00b69** [comment]
Imagine adding guides without even verifying whether they work

**Comment by remtrik** [comment]
Imagine not telling why they are considered non functional/not working and just answering "No" every time

**Review by NetuserPRO — APPROVED** [review]

**Comment by n00b69** [comment]
- V50 guide is full of broken links
- V50 guide does not explain the user how to boot Windows
- V50 guide leaves users with a phone that doesn't even boot Android if they follow the exact steps
- Both guides don't even install Windows due to the incredibly wrong commit that Special Ice made 3 days ago
- V50 guide uses the wrong instructions for drivers
- Funny how both of you keep larping about my guides being not functional while you push this mess onto everyone
- Formatting Win and Esp twice is also redundant
- Also the G8x guide is a carbon copy of an older version of my G8x guide, so why were the credits removed?

**Comment by remtrik** [comment]
Well that's sounds like a reasonable answer. Thanks for notifying us, everything will be fixed ASAP :)

**Comment by Icesito68** [comment]
@remtrik Well, I think I should clarify that there have been internal communication errors.
The LG guides are not yet ready to be official, (That's why at no time in the LG group have they become official) I myself am aware that everything is broken at this moment, I am sorry that I have not had time to fix it, when I return from vacation everything will be fixed to leave it ready

**Pull request closed without merging**
